### ISSUE TITLE
Constantly having to redownload models

### ISSUE THREAD

**Issue by JohnnyRacer** [ai-forever/ru-dalle#113]
Hi, I've noticed that running it on a local jupyter instance will always redownload the model again. Is there a way I can avoid this as  I don't want to be waiting for it to finish everytime. Thanks/

**Comment by nerdyrodent** [comment]
You can specify your cache directory, rather than using /tmp

**Comment by JohnnyRacer** [comment]
Thanks a lot, that was exactly the issue.
