### ISSUE TITLE
Bad syntax in collab

### ISSUE THREAD

**Issue by Jakeukalane** [ai-forever/ru-dalle#122]
In https://colab.research.google.com/drive/1wGE-046et27oHvNlBNPH07qrEQNE04PQ?usp=sharing#scrollTo=GdOYJvwZSB-D

it should be a couple of quotes (") in the text parameter:

text = Что бы ни # @param 

Should be:

text = "Что бы ни" # @param 

Thanks!

**Comment by Jakeukalane** [comment]
So: "do not use the English text for inference, you should use translation to Russian, or you can use directly Russian text". Could be added. **Quotes are needed for correct execution**.

**Comment by NastyaMittseva** [comment]
We corrected errors and updated the minimal example.
