### ISSUE TITLE
Training other languages

### ISSUE THREAD

**Issue by loretoparisi** [ai-forever/ru-dalle#17]
Hello, how to train other languages? Thanks

**Comment by TatianaShavrina** [comment]
@loretoparisi for faster prototyping, I would suggest using automatic translation to Russian, for example, with translators lib

We used about 120 million pairs of texts and images, deduplicated and filtered, to train the model. We will post the survey soon

**Comment by abrichr** [comment]
It seems to work for at least some english phrases as well, e.g.:

> 'the quick brown fox jumps over the lazy dog'

![image](https://user-images.githubusercontent.com/96320670/152665747-b35b5245-6d11-47e6-bebd-8e7f57561df7.png)

![image](https://user-images.githubusercontent.com/96320670/152665751-7424c416-b131-41e1-8885-669b4fbbab89.png)

![image](https://user-images.githubusercontent.com/96320670/152665754-5086fb41-382f-46b2-8ec3-9720c912f7ca.png)
