### ISSUE TITLE
MultiGPU support ETA?

### ISSUE THREAD

**Issue by StrangeTcy** [ai-forever/ru-dalle#46]
I'd like to finetune my own model with your code, but the `DalleModel` as it is now doesn't seem to support the pytorch `DistributedDataParallel` wrapper.
Do you plan to add such an option?

**Comment by shonenkov** [comment]
@StrangeTcy good evening!

finetuning example on free colab you can find here:
**Finetuning example**
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1Tb7J4PvvegWOybPfUubl5O7m5I24CBg5?usp=sharing)

it doesn't support DDP, but feel free add these features 

we would like to share full training code after publish paper :)
