### ISSUE TITLE
Question about hard code part in model.py

### ISSUE THREAD

**Issue by vxzcorporation** [ai-forever/ru-dalle#74]
Hi there :)
First of all, I really want to thank you for sharing such a great work to the public. Because of your works, it was able to experiment and research text to image studies. Great Job!

I have a question about hard code part in model.py(from line 101 to line 116). 
My question is 'What is the purpose of the hard code part?'
Is there a specific reason you guys put that part?

That is my question. I thank you again for the great works! I hope you guy early happy Christmas and a happy New Year!
![스크린샷 2021-12-03 오후 4 45 41](https://user-images.githubusercontent.com/92016110/144565676-d883185c-5546-48cf-9d25-f915b3b34ec0.png)

**Comment by shonenkov** [comment]
@vxzcorporation thanks for your feedback :) 

double BOS token will be fixed with new version of model  checkpoint, sorry. 

if you remove it without more training, ruDALLE loses some skills about colors and maybe another characteristics
