### ISSUE TITLE
should use_cache=True be used for image prompts?

### ISSUE THREAD

**Issue by eyaler** [ai-forever/ru-dalle#89]
should we now use use_cache=True for image prompts? I was using the latest code but with use_cache=False. after changing results look the same but it is 10x faster...
is there any reason to use use_cache=False in some conditions?

**Comment by shonenkov** [comment]
you can use param use_cache=True with image_prompt ;) thanks a lot @oriBetelgeuse for fix here: https://github.com/sberbank-ai/ru-dalle/pull/37
